"""initial schema: deputies, commissions, memberships, meetings, attendances

Revision ID: a5064c40c64f
Revises: 
Create Date: 2026-09-03 19:07:13.813069
"""

import sqlalchemy as sa

from alembic import op

revision = "a5064c40c64f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "deputies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("party", sa.String(length=120), nullable=True),
        sa.Column("election_district", sa.String(length=120), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "commission_memberships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("commission_id", sa.Integer(), nullable=False),
        sa.Column("deputy_id", sa.Integer(), nullable=False),
        sa.Column("is_chair", sa.Boolean(), nullable=False),
        sa.Column("joined_at", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(["commission_id"], ["commissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["deputy_id"], ["deputies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("commission_id", "deputy_id", name="uq_membership_pair"),
    )
    op.create_table(
        "meetings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("commission_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("scheduled", "held", "cancelled", name="meetingstatus"),
            nullable=False,
        ),
        sa.Column("agenda", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["commission_id"], ["commissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "attendances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("deputy_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("present", "absent", "excused", name="attendancestatus"),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["deputy_id"], ["deputies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("meeting_id", "deputy_id", name="uq_attendance_pair"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("attendances")
    op.drop_table("meetings")
    op.drop_table("commission_memberships")
    op.drop_table("deputies")
    op.drop_table("commissions")
    # ### end Alembic commands ###
